server:
  port: ${PORT:8080}

messages:
  home: Salut tout le monde !

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: HTML
    #prefix: /templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
    #servlet:
     # content-type: text/html